### PR TITLE
Parse decl-less layout as verbatim. Fixes #22, #29

### LINKED ISSUE #22: Parse error from GLSL compute shader
I got Parse error from following GLSL compute shader.

test.cs:
```glsl
#version 450

layout(local_size_x = 32) in;

void main(){
}
```

Output:
```
Parse error: Error in test.cs: Ln: 3 Col: 29
layout(local_size_x = 32) in;
                            ^
Expecting: Type qualifier, identifier, 'layout' or 'struct'

   場所 Parse.ParseImpl.runParser@347.Invoke(String message)
   場所 Microsoft.FSharp.Core.PrintfImpl.go@523-3[b,c,d](String fmt, Int32 len, FSharpFunc`2 outputChar, FSharpFunc`2 outa, b os
,
FSharpFunc`2 finalize, FSharpList`1 args, Int32 i)
   場所 Microsoft.FSharp.Core.PrintfImpl.run@521[b,c,d](FSharpFunc`2 initialize, String fmt, Int32 len, FSharpList`1 args)
   場所 <StartupCode$FSharp-Core>.$Reflect.Invoke@720-4.Invoke(T1 inp)
   場所 main.minify(String filename, String content)
   場所 main.run(String[] files)
```

### PR DESCRIPTION
**Pull request by eldritchconundrum**

### CODE REVIEW

File: src/parse.fs [hunk 1]
```diff
@@ -213,15 +212,17 @@ type private ParseImpl() =
...
         let generic = ch '<' >>. manyCharsTill anyChar (ch '>')
                    |> opt
                    |>> (function Some s -> "<" + s + ">" | None -> "")
         let typeName = pipe2 (ident |>> (fun id -> id.Name)) generic (+)
         let typeSpec = structSpecifier <|> (typeName |>> Ast.TypeName)
         let arraySizes = many (between (ch '[') (ch ']') expr)
-        pipe4 qualifier typeSpec generic arraySizes (fun tyQ name _ sizes -> Ast.makeType name tyQ sizes)
+        pipe4 hlslQualifier typeSpec generic arraySizes (fun tyQ name _ sizes -> Ast.makeType name tyQ sizes)
 
+    let qualifier = if options.hlsl then hlslQualifier else glslQualifier
```
Comment (laurentlb) [inline src/parse.fs:225]: It looks like `qualifier` is a global value that will be evaluated once at the beginning of the program.
You might have to create a parser like `specifiedType` or create a function.

**Review by laurentlb — APPROVED** [review]
